# Rahman Scraper - DIAGNOSTIC VERSION

**Step 1**: First we'll inspect the HTML structure

**Step 2**: Then we'll write the scraper based on what we find

**IMPORTANT**: Run this in Kaggle (needs internet access)

## Install Libraries

In [1]:
!pip install requests beautifulsoup4 pandas lxml -q

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import time
from IPython.display import display, HTML

print("✓ Libraries imported")

✓ Libraries imported

# STEP 1: INSPECT HTML STRUCTURE

**Run this cell first and examine the output carefully**

In [3]:
# Fetch the search page
url = "https://corpus.quran.com/search.jsp?q=%D8%B1%D8%AD%D9%85%D8%A7%D9%86&page=0"

print("=" * 70)
print("FETCHING HTML FROM corpus.quran.com")
print("=" * 70)
print(f"URL: {url}\n")

try:
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    
    response = requests.get(url, headers=headers, timeout=30)
    print(f"✓ Status Code: {response.status_code}")
    print(f"✓ Response Length: {len(response.text)} characters\n")
    
    soup = BeautifulSoup(response.text, 'html.parser')
    
    print("=" * 70)
    print("HTML STRUCTURE ANALYSIS")
    print("=" * 70)
    
    # 1. Count tables
    tables = soup.find_all('table')
    print(f"\n1. Tables found: {len(tables)}")
    for i, table in enumerate(tables[:3]):  # First 3 tables
        print(f"   Table {i}: {table.get('class')} - {table.get('id')}")
    
    # 2. Count rows
    rows = soup.find_all('tr')
    print(f"\n2. Total <tr> rows found: {len(rows)}")
    
    # 3. Look for verse references
    verse_pattern = re.compile(r'\(?\d+:\d+:\d+\)?')
    all_text = soup.get_text()
    verse_matches = verse_pattern.findall(all_text)
    print(f"\n3. Verse references found (X:Y:Z format): {len(verse_matches)}")
    if verse_matches:
        print(f"   Examples: {verse_matches[:5]}")
    
    # 4. Look for links with verse references
    links = soup.find_all('a', href=True)
    verse_links = [link for link in links if verse_pattern.search(link.text)]
    print(f"\n4. Links with verse references: {len(verse_links)}")
    if verse_links:
        print("   First 3 examples:")
        for link in verse_links[:3]:
            print(f"     - Text: '{link.text.strip()}' | Href: {link.get('href')}")
    
    # 5. Look for Arabic text
    arabic_divs = soup.find_all('div', class_='arabic')
    print(f"\n5. Divs with class='arabic': {len(arabic_divs)}")
    if arabic_divs:
        print(f"   First example: {arabic_divs[0].text.strip()[:50]}...")
    
    # 6. Check for specific class names
    print(f"\n6. Checking common class names:")
    for class_name in ['result', 'search-result', 'verse', 'ayah', 'location']:
        elements = soup.find_all(class_=class_name)
        if elements:
            print(f"   - class='{class_name}': {len(elements)} found")
    
    print("\n" + "=" * 70)
    print("SAMPLE HTML SNIPPET (First 3000 characters)")
    print("=" * 70)
    print(response.text[:3000])
    
    print("\n" + "=" * 70)
    print("FIRST TABLE STRUCTURE (if exists)")
    print("=" * 70)
    if tables:
        first_table = tables[0]
        print(f"\nTable HTML:\n{first_table.prettify()[:2000]}")
        
        # Get first few rows
        table_rows = first_table.find_all('tr')[:5]
        print(f"\n\nFirst {len(table_rows)} rows structure:")
        for i, row in enumerate(table_rows):
            cells = row.find_all(['td', 'th'])
            print(f"\nRow {i}: {len(cells)} cells")
            for j, cell in enumerate(cells):
                print(f"  Cell {j}: {cell.text.strip()[:80]}")
    
    print("\n" + "=" * 70)
    print("✓ INSPECTION COMPLETE")
    print("=" * 70)
    print("\nREVIEW THE OUTPUT ABOVE TO UNDERSTAND THE HTML STRUCTURE")
    print("Then run the next cells to scrape based on what we found.")
    
except Exception as e:
    print(f"\n✗ ERROR: {e}")
    import traceback
    print("\nFull error:")
    traceback.print_exc()

======================================================================
FETCHING HTML FROM corpus.quran.com
======================================================================
URL: https://corpus.quran.com/search.jsp?q=%D8%B1%D8%AD%D9%85%D8%A7%D9%86&page=0

✓ Status Code: 200
✓ Response Length: 22440 characters

======================================================================
HTML STRUCTURE ANALYSIS
======================================================================

1. Tables found: 4
   Table 0: ['toolbar'] - None
   Table 1: ['pageTemplate'] - None
   Table 2: ['menu'] - None

2. Total <tr> rows found: 67

3. Verse references found (X:Y:Z format): 50
   Examples: ['(1:1:3)', '(1:3:1)', '(2:163:8)', '(13:30:17)', '(17:110:6)']

4. Links with verse references: 0

5. Divs with class='arabic': 0

6. Checking common class names:

======================================================================
SAMPLE HTML SNIPPET (First 3000 characters)
======================================================================












<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
<title>The Quranic Arabic Corpus - Quran Search</title>
<link href="/css/main.css" type="text/css" rel="stylesheet" />
<script type="text/javascript">function search() { var e = document.getElementById("searchTextBox");var url = "/search.jsp?q=" + encodeURIComponent(e.value);document.location.href = url;}</script>
<script type="text/javascript" src="/javascript/main.js"></script>

	<style type="text/css">
table.resultTable {
	margin-top: 1em;
}

table.resultTable td {
	border-bottom: 1px dashed rgb(180, 180, 180);
	padding-top: 1em;
	padding-bottom: 1em;
}

table.resultTable p.arabic,
table.resultTable p.translation {
	margin-left: 1em;
	margin-right: 1em;
	margin-top: 1em;
	margin-bottom: 1em;
}

table.resultTable p.arabic u,
table.resultTable p.result u {
	text-decoration: none;
	background: yellow;
}

table.resultTable p.arabic {
	font: 1.4em Traditional Arabic;
	color: rgb(50, 150, 50);
	direction: rtl;
}

table.resultTable p.translation {
	font-size:0.833em;
}
</style>

	<script type="text/javascript">
	function toggleOptions() {
		var element = document.getElementById('searchOptions');
		var isVisible = element.style.display != 'none';
		element.style.display = !isVisible ? '' : 'none';

		document.getElementById('optionsLink').innerHTML = !isVisible ? 'Hide options'
				: 'Show options';
		document.getElementById('optionsImage').src = !isVisible ? '/images/collapse.png'
				: '/images/expand.png';
	}
</script>


</head>
<body>
<table border="0" cellpadding="0" cellspacing="0" class="toolbar">
	<tr>
		<td class="toolbarLeft">&nbsp;</td>
		<td class="toolbarRight"><a href="http://www.quran.com">Qur'an</a>
		| <span>Word by Word</span> | <a href="http://www.quranicaudio.com">Audio</a>
		| <a href="http://www.waqt.org">Prayer Times</a></td>
	</tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" class="pageTemplate">
	<tr>
		<td class="logo1" rowspan="2"><a href="/"><img
			src="/images/logo.png" /></a></td>
		<td class="pad" rowspan="2">__</td>
		<td class="userBox"><img src="/images/person2.gif" /> <a href="/login.jsp">Sign In</a></td>
		<td class="searchBox"><a href="/searchhelp.jsp">Search</a> <input
			type="text" size="20" id="searchTextBox"
			onkeypress="if(event.keyCode == 13) { search(); return false; }" />
		<input type="button" value="Go" onclick="search();" /></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td class="leedsLogo"><!--  <a
			href="http://www.comp.leeds.ac.uk/arabic"><img
			src="/images/leeds.png" /></a>--></td>
	</tr>
	<tr>
		<td class="logoPad"><a href="/"><img src="/images/quran.jpeg"></a></td>
		<td class="pad">__</td>
		<td class="title" colspan="2">
		<h2>Quran Search</h2>
		</td>
	</tr>
	<t

======================================================================
FIRST TABLE STRUCTURE (if exists)
======================================================================

Table HTML:
<table border="0" cellpadding="0" cellspacing="0" class="toolbar">
 <tr>
  <td class="toolbarLeft">
  </td>
  <td class="toolbarRight">
   <a href="http://www.quran.com">
    Qur'an
   </a>
   |
   <span>
    Word by Word
   </span>
   |
   <a href="http://www.quranicaudio.com">
    Audio
   </a>
   |
   <a href="http://www.waqt.org">
    Prayer Times
   </a>
  </td>
 </tr>
</table>



First 1 rows structure:

Row 0: 2 cells
  Cell 0:
  Cell 1: Qur'an
		| Word by Word | Audio
		| Prayer Times

======================================================================
✓ INSPECTION COMPLETE
======================================================================

REVIEW THE OUTPUT ABOVE TO UNDERSTAND THE HTML STRUCTURE
Then run the next cells to scrape based on what we found.

# STEP 2: SCRAPER FUNCTION

**After reviewing the HTML structure above, run these cells**

We'll try multiple parsing strategies:

In [4]:
def scrape_rahman_adaptive(page=0):
    """
    Adaptive scraper that tries multiple strategies
    """
    url = f"https://corpus.quran.com/search.jsp?q=%D8%B1%D8%AD%D9%85%D8%A7%D9%86&page={page}"
    
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    }
    
    try:
        response = requests.get(url, headers=headers, timeout=30)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'html.parser')
        
        results = []
        verse_pattern = re.compile(r'(\d+):(\d+):(\d+)')
        
        # STRATEGY 1: Find all links with verse patterns
        print("  Strategy 1: Looking for verse links...")
        links = soup.find_all('a', href=True)
        for link in links:
            match = verse_pattern.search(link.text)
            if match:
                surah = int(match.group(1))
                ayah = int(match.group(2))
                word_pos = int(match.group(3))
                
                # Try to find the parent row
                parent_row = link.find_parent('tr')
                if parent_row:
                    cells = parent_row.find_all('td')
                    
                    # Get Arabic text
                    arabic_text = ""
                    for cell in cells:
                        arabic_div = cell.find('div', class_='arabic')
                        if arabic_div:
                            arabic_text = arabic_div.text.strip()
                            break
                    
                    # Get translation (usually in a later cell)
                    translation = ""
                    if len(cells) > 2:
                        translation = cells[2].text.strip()
                    
                    results.append({
                        'surah': surah,
                        'ayah': ayah,
                        'word_position': word_pos,
                        'location': f"{surah}:{ayah}:{word_pos}",
                        'arabic_text': arabic_text,
                        'translation': translation,
                        'method': 'link_search'
                    })
        
        print(f"    Found {len(results)} results via link search")
        
        # STRATEGY 2: If no results, try table row iteration
        if len(results) == 0:
            print("  Strategy 2: Checking table rows...")
            tables = soup.find_all('table')
            
            for table in tables:
                rows = table.find_all('tr')
                
                for row in rows:
                    cells = row.find_all('td')
                    
                    if len(cells) >= 2:
                        # First cell might have location
                        first_cell_text = cells[0].get_text()
                        match = verse_pattern.search(first_cell_text)
                        
                        if match:
                            surah = int(match.group(1))
                            ayah = int(match.group(2))
                            word_pos = int(match.group(3))
                            
                            arabic_text = ""
                            for cell in cells:
                                arabic_div = cell.find('div', class_='arabic')
                                if arabic_div:
                                    arabic_text = arabic_div.text.strip()
                                    break
                            
                            translation = cells[2].text.strip() if len(cells) > 2 else ""
                            
                            results.append({
                                'surah': surah,
                                'ayah': ayah,
                                'word_position': word_pos,
                                'location': f"{surah}:{ayah}:{word_pos}",
                                'arabic_text': arabic_text,
                                'translation': translation,
                                'method': 'table_row'
                            })
            
            print(f"    Found {len(results)} results via table rows")
        
        # STRATEGY 3: If still no results, try regex on all text
        if len(results) == 0:
            print("  Strategy 3: Using regex on all page text...")
            all_text = soup.get_text()
            matches = verse_pattern.findall(all_text)
            
            for match in matches:
                results.append({
                    'surah': int(match[0]),
                    'ayah': int(match[1]),
                    'word_position': int(match[2]),
                    'location': f"{match[0]}:{match[1]}:{match[2]}",
                    'arabic_text': '',
                    'translation': '',
                    'method': 'regex_text'
                })
            
            print(f"    Found {len(matches)} verse references via regex")
        
        return results
        
    except Exception as e:
        print(f"  ✗ Error: {e}")
        return []

print("✓ Adaptive scraper function defined")

✓ Adaptive scraper function defined

# STEP 3: TEST SCRAPER ON FIRST PAGE

In [5]:
print("Testing scraper on page 0...\n")
test_results = scrape_rahman_adaptive(page=0)

print(f"\n✓ Test complete: Found {len(test_results)} results")

if test_results:
    print("\nFirst 5 results:")
    for i, result in enumerate(test_results[:5]):
        print(f"\n{i+1}. {result['location']}")
        print(f"   Method: {result['method']}")
        print(f"   Arabic: {result['arabic_text'][:50]}..." if result['arabic_text'] else "   Arabic: (none)")
    
    # Create DataFrame
    df_test = pd.DataFrame(test_results)
    display(df_test.head(10))
else:
    print("\n⚠ WARNING: No results found!")
    print("\nThe HTML structure might be different than expected.")
    print("Go back and review the HTML inspection output above.")
    print("\nOr try this alternative: manually inspect the page source:")
    print("1. Open: https://corpus.quran.com/search.jsp?q=%D8%B1%D8%AD%D9%85%D8%A7%D9%86")
    print("2. Right-click → View Page Source")
    print("3. Look for how the results are structured")

Testing scraper on page 0...

  Strategy 1: Looking for verse links...
    Found 0 results via link search
  Strategy 2: Checking table rows...
    Found 100 results via table rows

✓ Test complete: Found 100 results

First 5 results:

1. 1:1:3
   Method: table_row
   Arabic: (none)

2. 1:3:1
   Method: table_row
   Arabic: (none)

3. 2:163:8
   Method: table_row
   Arabic: (none)

4. 13:30:17
   Method: table_row
   Arabic: (none)

5. 17:110:6
   Method: table_row
   Arabic: (none)

,surah,ayah,word_position,location,arabic_text,translation,method
0,1,1,3,1:1:3,,بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ,table_row
1,1,3,1,1:3:1,,الرَّحْمَٰنِ الرَّحِيمِ,table_row
2,2,163,8,2:163:8,,وَإِلَٰهُكُمْ إِلَٰهٌ وَاحِدٌ لَا إِلَٰهَ إِلّ...,table_row
3,13,30,17,13:30:17,,لِتَتْلُوَ عَلَيْهِمُ الَّذِي أَوْحَيْنَا إِلَ...,table_row
4,17,110,6,17:110:6,,قُلِ ادْعُوا اللَّهَ أَوِ ادْعُوا الرَّحْمَٰنَ,table_row
5,19,18,4,19:18:4,,قَالَتْ إِنِّي أَعُوذُ بِالرَّحْمَٰنِ مِنْكَ إ...,table_row
6,19,26,13,19:26:13,,إِنِّي نَذَرْتُ لِلرَّحْمَٰنِ صَوْمًا فَلَنْ أ...,table_row
7,19,44,8,19:44:8,,يَا أَبَتِ لَا تَعْبُدِ الشَّيْطَانَ إِنَّ الش...,table_row
8,19,45,8,19:45:8,,يَا أَبَتِ إِنِّي أَخَافُ أَنْ يَمَسَّكَ عَذَا...,table_row
9,19,58,26,19:58:26,,إِذَا تُتْلَىٰ عَلَيْهِمْ آيَاتُ الرَّحْمَٰنِ ...,table_row

# STEP 4: SCRAPE ALL PAGES

**Only run this if the test above found results!**

In [6]:
def scrape_all_rahman_pages():
    """
    Scrape all pages until no more results
    """
    print("=" * 70)
    print("SCRAPING ALL RAHMAN OCCURRENCES")
    print("=" * 70)
    
    all_results = []
    seen_locations = set()
    page = 0
    max_pages = 10
    
    while page < max_pages:
        print(f"\nPage {page}:")
        page_results = scrape_rahman_adaptive(page)
        
        if not page_results:
            print(f"  → No results, stopping.")
            break
        
        # Add unique results
        new_count = 0
        for result in page_results:
            loc = result['location']
            if loc not in seen_locations:
                seen_locations.add(loc)
                all_results.append(result)
                new_count += 1
        
        print(f"  ✓ Added {new_count} new unique results")
        page += 1
        time.sleep(1)
    
    print("\n" + "=" * 70)
    print(f"SCRAPING COMPLETE: {len(all_results)} unique results")
    print("=" * 70)
    
    return all_results

# Run scraper
rahman_results = scrape_all_rahman_pages()

# Create DataFrame
df_rahman_raw = pd.DataFrame(rahman_results)
print(f"\n✓ Created DataFrame with {len(df_rahman_raw)} rows")
display(df_rahman_raw.head(15))

======================================================================
SCRAPING ALL RAHMAN OCCURRENCES
======================================================================

Page 0:
  Strategy 1: Looking for verse links...
    Found 0 results via link search
  Strategy 2: Checking table rows...
    Found 100 results via table rows
  ✓ Added 50 new unique results

Page 1:
  Strategy 1: Looking for verse links...
    Found 0 results via link search
  Strategy 2: Checking table rows...
    Found 100 results via table rows
  ✓ Added 0 new unique results

Page 2:
  Strategy 1: Looking for verse links...
    Found 0 results via link search
  Strategy 2: Checking table rows...
    Found 14 results via table rows
  ✓ Added 7 new unique results

Page 3:
  Strategy 1: Looking for verse links...
    Found 0 results via link search
  Strategy 2: Checking table rows...
    Found 14 results via table rows
  ✓ Added 0 new unique results

Page 4:
  Strategy 1: Looking for verse links...
    Found 0 results via link search
  Strategy 2: Checking table rows...
    Found 14 results via table rows
  ✓ Added 0 new unique results

Page 5:
  Strategy 1: Looking for verse links...
    Found 0 results via link search
  Strategy 2: Checking table rows...
    Found 14 results via table rows
  ✓ Added 0 new unique results

Page 6:
  Strategy 1: Looking for verse links...
    Found 0 results via link search
  Strategy 2: Checking table rows...
    Found 14 results via table rows
  ✓ Added 0 new unique results

Page 7:
  Strategy 1: Looking for verse links...
    Found 0 results via link search
  Strategy 2: Checking table rows...
    Found 14 results via table rows
  ✓ Added 0 new unique results

Page 8:
  Strategy 1: Looking for verse links...
    Found 0 results via link search
  Strategy 2: Checking table rows...
    Found 14 results via table rows
  ✓ Added 0 new unique results

Page 9:
  Strategy 1: Looking for verse links...
    Found 0 results via link search
  Strategy 2: Checking table rows...
    Found 14 results via table rows
  ✓ Added 0 new unique results

======================================================================
SCRAPING COMPLETE: 57 unique results
======================================================================

✓ Created DataFrame with 57 rows

,surah,ayah,word_position,location,arabic_text,translation,method
0,1,1,3,1:1:3,,بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ,table_row
1,1,3,1,1:3:1,,الرَّحْمَٰنِ الرَّحِيمِ,table_row
2,2,163,8,2:163:8,,وَإِلَٰهُكُمْ إِلَٰهٌ وَاحِدٌ لَا إِلَٰهَ إِلّ...,table_row
3,13,30,17,13:30:17,,لِتَتْلُوَ عَلَيْهِمُ الَّذِي أَوْحَيْنَا إِلَ...,table_row
4,17,110,6,17:110:6,,قُلِ ادْعُوا اللَّهَ أَوِ ادْعُوا الرَّحْمَٰنَ,table_row
5,19,18,4,19:18:4,,قَالَتْ إِنِّي أَعُوذُ بِالرَّحْمَٰنِ مِنْكَ إ...,table_row
6,19,26,13,19:26:13,,إِنِّي نَذَرْتُ لِلرَّحْمَٰنِ صَوْمًا فَلَنْ أ...,table_row
7,19,44,8,19:44:8,,يَا أَبَتِ لَا تَعْبُدِ الشَّيْطَانَ إِنَّ الش...,table_row
8,19,45,8,19:45:8,,يَا أَبَتِ إِنِّي أَخَافُ أَنْ يَمَسَّكَ عَذَا...,table_row
9,19,58,26,19:58:26,,إِذَا تُتْلَىٰ عَلَيْهِمْ آيَاتُ الرَّحْمَٰنِ ...,table_row
10,19,61,5,19:61:5,,جَنَّاتِ عَدْنٍ الَّتِي وَعَدَ الرَّحْمَٰنُ عِ...,table_row
11,19,69,9,19:69:9,,ثُمَّ لَنَنْزِعَنَّ مِنْ كُلِّ شِيعَةٍ أَيُّهُ...,table_row
12,19,75,8,19:75:8,,قُلْ مَنْ كَانَ فِي الضَّلَالَةِ فَلْيَمْدُدْ ...,table_row
13,19,78,6,19:78:6,,أَطَّلَعَ الْغَيْبَ أَمِ اتَّخَذَ عِنْدَ الرَّ...,table_row
14,19,85,5,19:85:5,,يَوْمَ نَحْشُرُ الْمُتَّقِينَ إِلَى الرَّحْمَٰ...,table_row

# STEP 5: GROUP BY VERSE

In [7]:
if len(df_rahman_raw) > 0:
    # Group by verse
    rahman_by_verse = df_rahman_raw.groupby(['surah', 'ayah']).agg({
        'word_position': lambda x: sorted(list(x)),
        'arabic_text': 'first',
        'translation': 'first'
    }).reset_index()
    
    rahman_by_verse['rahman_frequency'] = rahman_by_verse['word_position'].apply(len)
    rahman_by_verse.columns = ['surah_no', 'ayah_no', 'rahman_word_locations', 
                                'arabic_text', 'translation', 'rahman_frequency']
    
    print(f"Grouped into {len(rahman_by_verse)} unique verses")
    print(f"Total Rahman occurrences: {rahman_by_verse['rahman_frequency'].sum()}")
    
    display(rahman_by_verse.head(20))
else:
    print("⚠ No data to group!")

Grouped into 56 unique verses
Total Rahman occurrences: 57

,surah_no,ayah_no,rahman_word_locations,arabic_text,translation,rahman_frequency
0,1,1,[3],,بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ,1
1,1,3,[1],,الرَّحْمَٰنِ الرَّحِيمِ,1
2,2,163,[8],,وَإِلَٰهُكُمْ إِلَٰهٌ وَاحِدٌ لَا إِلَٰهَ إِلّ...,1
3,13,30,[17],,لِتَتْلُوَ عَلَيْهِمُ الَّذِي أَوْحَيْنَا إِلَ...,1
4,17,110,[6],,قُلِ ادْعُوا اللَّهَ أَوِ ادْعُوا الرَّحْمَٰنَ,1
5,19,18,[4],,قَالَتْ إِنِّي أَعُوذُ بِالرَّحْمَٰنِ مِنْكَ إ...,1
6,19,26,[13],,إِنِّي نَذَرْتُ لِلرَّحْمَٰنِ صَوْمًا فَلَنْ أ...,1
7,19,44,[8],,يَا أَبَتِ لَا تَعْبُدِ الشَّيْطَانَ إِنَّ الش...,1
8,19,45,[8],,يَا أَبَتِ إِنِّي أَخَافُ أَنْ يَمَسَّكَ عَذَا...,1
9,19,58,[26],,إِذَا تُتْلَىٰ عَلَيْهِمْ آيَاتُ الرَّحْمَٰنِ ...,1
10,19,61,[5],,جَنَّاتِ عَدْنٍ الَّتِي وَعَدَ الرَّحْمَٰنُ عِ...,1
11,19,69,[9],,ثُمَّ لَنَنْزِعَنَّ مِنْ كُلِّ شِيعَةٍ أَيُّهُ...,1
12,19,75,[8],,قُلْ مَنْ كَانَ فِي الضَّلَالَةِ فَلْيَمْدُدْ ...,1
13,19,78,[6],,أَطَّلَعَ الْغَيْبَ أَمِ اتَّخَذَ عِنْدَ الرَّ...,1
14,19,85,[5],,يَوْمَ نَحْشُرُ الْمُتَّقِينَ إِلَى الرَّحْمَٰ...,1
15,19,87,[8],,لَا يَمْلِكُونَ الشَّفَاعَةَ إِلَّا مَنِ اتَّخ...,1
16,19,88,[3],,وَقَالُوا اتَّخَذَ الرَّحْمَٰنُ وَلَدًا,1
17,19,91,[3],,أَنْ دَعَوْا لِلرَّحْمَٰنِ وَلَدًا,1
18,19,92,[3],,وَمَا يَنْبَغِي لِلرَّحْمَٰنِ أَنْ يَتَّخِذَ و...,1
19,19,93,[9],,إِنْ كُلُّ مَنْ فِي السَّمَاوَاتِ وَالْأَرْضِ ...,1

# STEP 6: SAVE RESULTS

In [8]:
if len(df_rahman_raw) > 0:
    # Save raw data
    df_rahman_raw.to_csv('rahman_raw_scraped.csv', index=False, encoding='utf-8-sig')
    print("✓ Saved: rahman_raw_scraped.csv")
    
    # Save grouped data
    rahman_by_verse.to_csv('rahman_frequency_scraped.csv', index=False, encoding='utf-8-sig')
    print("✓ Saved: rahman_frequency_scraped.csv")
    
    print(f"\nTotal verses with Rahman: {len(rahman_by_verse)}")
    print(f"Total Rahman word occurrences: {rahman_by_verse['rahman_frequency'].sum()}")
else:
    print("⚠ No results to save!")

✓ Saved: rahman_raw_scraped.csv
✓ Saved: rahman_frequency_scraped.csv

Total verses with Rahman: 56
Total Rahman word occurrences: 57

# STEP 7: MERGE WITH YOUR EXISTING CSV

In [9]:
# UPDATE THIS PATH to your actual file!
existing_csv_path = '/kaggle/input/datasets/axha241419/proper-noun-word-allah-extracted/quran_ayahs_cleaned (3).csv'

print(f"Loading: {existing_csv_path}")
df_existing = pd.read_csv(existing_csv_path)
print(f"✓ Loaded {len(df_existing)} rows")

# Merge
df_updated = df_existing.merge(
    rahman_by_verse[['surah_no', 'ayah_no', 'rahman_frequency', 'rahman_word_locations']],
    on=['surah_no', 'ayah_no'],
    how='left',
    suffixes=('_old', '_corrected')
)

# Use corrected data
if 'rahman_frequency_corrected' in df_updated.columns:
    df_updated['rahman_frequency'] = df_updated['rahman_frequency_corrected'].fillna(0).astype(int)
    df_updated.drop(['rahman_frequency_old', 'rahman_frequency_corrected'], axis=1, inplace=True, errors='ignore')

if 'rahman_word_locations_corrected' in df_updated.columns:
    df_updated['rahman_word_locations'] = df_updated['rahman_word_locations_corrected'].apply(
        lambda x: x if isinstance(x, list) else []
    )
    df_updated.drop(['rahman_word_locations_old', 'rahman_word_locations_corrected'], axis=1, inplace=True, errors='ignore')

# Update الرحمن_frequency if it exists
if 'الرحمن_frequency' in df_updated.columns:
    df_updated['الرحمن_frequency'] = df_updated['rahman_frequency']

# Save final file
final_output = 'quran_with_corrected_rahman.csv'
df_updated.to_csv(final_output, index=False, encoding='utf-8-sig')

print("\n" + "=" * 70)
print("✓ SUCCESS!")
print("=" * 70)
print(f"\nFinal CSV: {final_output}")
print(f"Total rows: {len(df_updated)}")
print(f"Verses with Rahman: {(df_updated['rahman_frequency'] > 0).sum()}")
print(f"Total Rahman occurrences: {df_updated['rahman_frequency'].sum()}")

# Show all Rahman verses
print("\nAll verses with Rahman:")
display(df_updated[df_updated['rahman_frequency'] > 0][[
    'surah_no', 'ayah_no', 'rahman_frequency', 'rahman_word_locations'
]].sort_values(['surah_no', 'ayah_no']))

Loading: /kaggle/input/datasets/axha241419/proper-noun-word-allah-extracted/quran_ayahs_cleaned (3).csv
✓ Loaded 6236 rows

======================================================================
✓ SUCCESS!
======================================================================

Final CSV: quran_with_corrected_rahman.csv
Total rows: 6236
Verses with Rahman: 56
Total Rahman occurrences: 57.0

All verses with Rahman:

      surah_no  ayah_no  rahman_frequency rahman_word_locations
0            1        1               1.0                   [3]
2            1        3               1.0                   [1]
169          2      163               1.0                   [8]
1736        13       30               1.0                  [17]
2138        17      110               1.0                   [6]
2267        19       18               1.0                   [4]
2275        19       26               1.0                  [13]
2293        19       44               1.0                   [8]
2294        19       45               1.0                   [8]
2307        19       58               1.0                  [26]
2310        19       61               1.0                   [5]
2318        19       69               1.0                   [9]
2324        19       75               1.0                   [8]
2327        19       78               1.0                   [6]
2334        19       85               1.0                   [5]
2336        19       87               1.0                   [8]
2337        19       88               1.0                   [3]
2340        19       91               1.0                   [3]
2341        19       92               1.0                   [3]
2342        19       93               1.0                   [9]
2345        19       96               1.0                   [8]
2352        20        5               1.0                   [1]
2437        20       90               1.0                  [13]
2455        20      108               1.0                   [9]
2456        20      109               1.0                   [9]
2508        21       26               1.0                   [3]
2518        21       36               1.0                  [15]
2524        21       42               1.0                   [7]
2594        21      112               1.0                   [6]
2880        25       26               1.0                   [4]
2913        25       59               1.0                  [14]
2914        25       60               2.0                [5, 8]
2917        25       63               1.0                   [2]
2936        26        5               1.0                   [6]
3188        27       30               1.0                   [7]
3715        36       11               1.0                   [7]
3719        36       15               1.0                   [9]
3727        36       23               1.0                   [7]
3756        36       52               1.0                  [10]
4219        41        2               1.0                   [3]
4341        43       17               1.0                   [6]
4343        43       19               1.0                   [6]
4344        43       20               1.0                   [4]
4357        43       33               1.0                  [10]
4360        43       36               1.0                   [5]
4369        43       45               1.0                  [11]
4405        43       81               1.0                   [4]
4662        50       33               1.0                   [3]
4901        55        1               1.0                   [1]
5147        59       22               1.0                  [12]
5243        67        3               1.0                  [10]
5259        67       19               1.0                  [11]
5260        67       20               1.0                  [10]
5269        67       29               1.0                   [3]
5708        78       37               1.0                   [6]
5709        78       38               1.0                  [12]